version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"

  mongodb:
    image: mongo
    ports:
     - "27017:27017"
